// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/system/v1/system.proto

package systemv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MetricSeries 是服务端预置的具名查询。
//
// 分段编号(进程 1-9 / 节点 10-19 / API 20-29 / 数据库 30-39)是为了以后
// 在某一段里加新项时不必打乱其他段,枚举值一旦发布就不能改。
type MetricSeries int32

const (
	MetricSeries_METRIC_SERIES_UNSPECIFIED MetricSeries = 0
	// ——— 本进程 ——— 来自 sysstat 推给 VM 的 process_* 量表
	MetricSeries_METRIC_SERIES_PROCESS_CPU        MetricSeries = 1 // 占 CPU 限额的百分比
	MetricSeries_METRIC_SERIES_PROCESS_MEMORY     MetricSeries = 2 // 常驻内存字节
	MetricSeries_METRIC_SERIES_PROCESS_GOROUTINES MetricSeries = 3 // goroutine 数
	MetricSeries_METRIC_SERIES_PROCESS_NETWORK    MetricSeries = 4 // 收发速率
	// ——— 所在节点 ——— 来自 otel collector 的 host_metrics
	// 这些是整台机器的口径,不是本进程的。两组同时展示是刻意的:
	// 进程自己很闲但节点被别的负载打满,同样会让配置中心变慢。
	MetricSeries_METRIC_SERIES_HOST_CPU     MetricSeries = 10
	MetricSeries_METRIC_SERIES_HOST_MEMORY  MetricSeries = 11
	MetricSeries_METRIC_SERIES_HOST_DISK    MetricSeries = 12
	MetricSeries_METRIC_SERIES_HOST_NETWORK MetricSeries = 13
	// ——— API ——— 来自 otelconnect 拦截器
	MetricSeries_METRIC_SERIES_API_LATENCY    MetricSeries = 20 // P50 / P95 / P99
	MetricSeries_METRIC_SERIES_API_THROUGHPUT MetricSeries = 21 // 每方法 QPS
	MetricSeries_METRIC_SERIES_API_ERROR_RATE MetricSeries = 22 // 非 OK 的 connect 错误码占比
	// ——— 数据库 ——— 来自 otelpgx
	MetricSeries_METRIC_SERIES_DB_LATENCY MetricSeries = 30
	MetricSeries_METRIC_SERIES_DB_POOL    MetricSeries = 31 // 连接池占用
)

// Enum value maps for MetricSeries.
var (
	MetricSeries_name = map[int32]string{
		0:  "METRIC_SERIES_UNSPECIFIED",
		1:  "METRIC_SERIES_PROCESS_CPU",
		2:  "METRIC_SERIES_PROCESS_MEMORY",
		3:  "METRIC_SERIES_PROCESS_GOROUTINES",
		4:  "METRIC_SERIES_PROCESS_NETWORK",
		10: "METRIC_SERIES_HOST_CPU",
		11: "METRIC_SERIES_HOST_MEMORY",
		12: "METRIC_SERIES_HOST_DISK",
		13: "METRIC_SERIES_HOST_NETWORK",
		20: "METRIC_SERIES_API_LATENCY",
		21: "METRIC_SERIES_API_THROUGHPUT",
		22: "METRIC_SERIES_API_ERROR_RATE",
		30: "METRIC_SERIES_DB_LATENCY",
		31: "METRIC_SERIES_DB_POOL",
	}
	MetricSeries_value = map[string]int32{
		"METRIC_SERIES_UNSPECIFIED":        0,
		"METRIC_SERIES_PROCESS_CPU":        1,
		"METRIC_SERIES_PROCESS_MEMORY":     2,
		"METRIC_SERIES_PROCESS_GOROUTINES": 3,
		"METRIC_SERIES_PROCESS_NETWORK":    4,
		"METRIC_SERIES_HOST_CPU":           10,
		"METRIC_SERIES_HOST_MEMORY":        11,
		"METRIC_SERIES_HOST_DISK":          12,
		"METRIC_SERIES_HOST_NETWORK":       13,
		"METRIC_SERIES_API_LATENCY":        20,
		"METRIC_SERIES_API_THROUGHPUT":     21,
		"METRIC_SERIES_API_ERROR_RATE":     22,
		"METRIC_SERIES_DB_LATENCY":         30,
		"METRIC_SERIES_DB_POOL":            31,
	}
)

func (x MetricSeries) Enum() *MetricSeries {
	p := new(MetricSeries)
	*p = x
	return p
}

func (x MetricSeries) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MetricSeries) Descriptor() protoreflect.EnumDescriptor {
	return file_api_system_v1_system_proto_enumTypes[0].Descriptor()
}

func (MetricSeries) Type() protoreflect.EnumType {
	return &file_api_system_v1_system_proto_enumTypes[0]
}

func (x MetricSeries) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MetricSeries.Descriptor instead.
func (MetricSeries) EnumDescriptor() ([]byte, []int) {
	return file_api_system_v1_system_proto_rawDescGZIP(), []int{0}
}

// 值的量纲。前端据此决定格式化方式(百分号 / KB-MB / ms / req/s),
// 而不是按 series 硬编码 —— 后者每加一条曲线都要改前端的 switch。
type MetricUnit int32

const (
	MetricUnit_METRIC_UNIT_UNSPECIFIED         MetricUnit = 0
	MetricUnit_METRIC_UNIT_PERCENT             MetricUnit = 1
	MetricUnit_METRIC_UNIT_BYTES               MetricUnit = 2
	MetricUnit_METRIC_UNIT_BYTES_PER_SECOND    MetricUnit = 3
	MetricUnit_METRIC_UNIT_MILLISECONDS        MetricUnit = 4
	MetricUnit_METRIC_UNIT_REQUESTS_PER_SECOND MetricUnit = 5
	MetricUnit_METRIC_UNIT_COUNT               MetricUnit = 6
)

// Enum value maps for MetricUnit.
var (
	MetricUnit_name = map[int32]string{
		0: "METRIC_UNIT_UNSPECIFIED",
		1: "METRIC_UNIT_PERCENT",
		2: "METRIC_UNIT_BYTES",
		3: "METRIC_UNIT_BYTES_PER_SECOND",
		4: "METRIC_UNIT_MILLISECONDS",
		5: "METRIC_UNIT_REQUESTS_PER_SECOND",
		6: "METRIC_UNIT_COUNT",
	}
	MetricUnit_value = map[string]int32{
		"METRIC_UNIT_UNSPECIFIED":         0,
		"METRIC_UNIT_PERCENT":             1,
		"METRIC_UNIT_BYTES":               2,
		"METRIC_UNIT_BYTES_PER_SECOND":    3,
		"METRIC_UNIT_MILLISECONDS":        4,
		"METRIC_UNIT_REQUESTS_PER_SECOND": 5,
		"METRIC_UNIT_COUNT":               6,
	}
)

func (x MetricUnit) Enum() *MetricUnit {
	p := new(MetricUnit)
	*p = x
	return p
}

func (x MetricUnit) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MetricUnit) Descriptor() protoreflect.EnumDescriptor {
	return file_api_system_v1_system_proto_enumTypes[1].Descriptor()
}

func (MetricUnit) Type() protoreflect.EnumType {
	return &file_api_system_v1_system_proto_enumTypes[1]
}

func (x MetricUnit) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MetricUnit.Descriptor instead.
func (MetricUnit) EnumDescriptor() ([]byte, []int) {
	return file_api_system_v1_system_proto_rawDescGZIP(), []int{1}
}

type GetSystemStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSystemStatusRequest) Reset() {
	*x = GetSystemStatusRequest{}
	mi := &file_api_system_v1_system_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSystemStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSystemStatusRequest) ProtoMessage() {}

func (x *GetSystemStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_system_v1_system_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSystemStatusRequest.ProtoReflect.Descriptor instead.
func (*GetSystemStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_system_v1_system_proto_rawDescGZIP(), []int{0}
}

type GetSystemStatusResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Process *ProcessStatus         `protobuf:"bytes,1,opt,name=process,proto3" json:"process,omitempty"`
	// 配置中心依赖的下游。与 /healthz 用的是同一组检查,
	// 免得「探针说健康、页面说挂了」这种自相矛盾。
	Dependencies []*DependencyStatus `protobuf:"bytes,2,rep,name=dependencies,proto3" json:"dependencies,omitempty"`
	Build        *BuildInfo          `protobuf:"bytes,3,opt,name=build,proto3" json:"build,omitempty"`
	// 为 false 时前端隐藏所有历史曲线并说明原因,而不是画一堆空图。
	MetricsBackendAvailable bool `protobuf:"varint,4,opt,name=metrics_backend_available,json=metricsBackendAvailable,proto3" json:"metrics_backend_available,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *GetSystemStatusResponse) Reset() {
	*x = GetSystemStatusResponse{}
	mi := &file_api_system_v1_system_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSystemStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSystemStatusResponse) ProtoMessage() {}

func (x *GetSystemStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_system_v1_system_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSystemStatusResponse.ProtoReflect.Descriptor instead.
func (*GetSystemStatusResponse) Descriptor() ([]byte, []int) {
	return file_api_system_v1_system_proto_rawDescGZIP(), []int{1}
}

func (x *GetSystemStatusResponse) GetProcess() *ProcessStatus {
	if x != nil {
		return x.Process
	}
	return nil
}

func (x *GetSystemStatusResponse) GetDependencies() []*DependencyStatus {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

func (x *GetSystemStatusResponse) GetBuild() *BuildInfo {
	if x != nil {
		return x.Build
	}
	return nil
}

func (x *GetSystemStatusResponse) GetMetricsBackendAvailable() bool {
	if x != nil {
		return x.MetricsBackendAvailable
	}
	return false
}

// ProcessStatus 是「本进程 / 本 Pod」的资源占用。
//
// 注意与 HOST_* 系列的区别:这里的分母是 cgroup 限额(k8s 的 limits),
// 不是宿主机规格。一个 limits.cpu=200m 的 Pod 把配额吃满时这里显示 100%,
// 而节点 CPU 可能才 5% —— 两个数都对,回答的是不同的问题。
type ProcessStatus struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CpuPercent       float64                `protobuf:"fixed64,1,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"` // 0..100,相对 cpu_limit_cores
	CpuLimitCores    float64                `protobuf:"fixed64,2,opt,name=cpu_limit_cores,json=cpuLimitCores,proto3" json:"cpu_limit_cores,omitempty"`
	MemoryRssBytes   int64                  `protobuf:"varint,3,opt,name=memory_rss_bytes,json=memoryRssBytes,proto3" json:"memory_rss_bytes,omitempty"`
	MemoryLimitBytes int64                  `protobuf:"varint,4,opt,name=memory_limit_bytes,json=memoryLimitBytes,proto3" json:"memory_limit_bytes,omitempty"`
	GoHeapBytes      int64                  `protobuf:"varint,5,opt,name=go_heap_bytes,json=goHeapBytes,proto3" json:"go_heap_bytes,omitempty"`
	Goroutines       int32                  `protobuf:"varint,6,opt,name=goroutines,proto3" json:"goroutines,omitempty"`
	GcCount          uint32                 `protobuf:"varint,7,opt,name=gc_count,json=gcCount,proto3" json:"gc_count,omitempty"`
	DiskPath         string                 `protobuf:"bytes,8,opt,name=disk_path,json=diskPath,proto3" json:"disk_path,omitempty"`
	DiskUsedBytes    int64                  `protobuf:"varint,9,opt,name=disk_used_bytes,json=diskUsedBytes,proto3" json:"disk_used_bytes,omitempty"`
	DiskTotalBytes   int64                  `protobuf:"varint,10,opt,name=disk_total_bytes,json=diskTotalBytes,proto3" json:"disk_total_bytes,omitempty"`
	NetRxBytesPerSec float64                `protobuf:"fixed64,11,opt,name=net_rx_bytes_per_sec,json=netRxBytesPerSec,proto3" json:"net_rx_bytes_per_sec,omitempty"`
	NetTxBytesPerSec float64                `protobuf:"fixed64,12,opt,name=net_tx_bytes_per_sec,json=netTxBytesPerSec,proto3" json:"net_tx_bytes_per_sec,omitempty"`
	// false 表示没读到 cgroup 限额,上面两个 limit 用的是整机规格。
	// 前端必须把这件事显示出来:否则开发机上看到的 0.3% 会被当成生产表现。
	LimitsFromCgroup bool                   `protobuf:"varint,13,opt,name=limits_from_cgroup,json=limitsFromCgroup,proto3" json:"limits_from_cgroup,omitempty"`
	SampledAt        *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=sampled_at,json=sampledAt,proto3" json:"sampled_at,omitempty"`
	Uptime           *durationpb.Duration   `protobuf:"bytes,15,opt,name=uptime,proto3" json:"uptime,omitempty"`
	// 本次采样中失败的子项。空表示全部正常。
	// 有值时前端把对应的卡片标灰,而不是显示 0 —— 0 和「没采到」不是一回事。
	Degraded      []string `protobuf:"bytes,16,rep,name=degraded,proto3" json:"degraded,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessStatus) Reset() {
	*x = ProcessStatus{}
	mi := &file_api_system_v1_system_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessStatus) ProtoMessage() {}

func (x *ProcessStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_system_v1_system_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessStatus.ProtoReflect.Descriptor instead.
func (*ProcessStatus) Descriptor() ([]byte, []int) {
	return file_api_system_v1_system_proto_rawDescGZIP(), []int{2}
}

func (x *ProcessStatus) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *ProcessStatus) GetCpuLimitCores() float64 {
	if x != nil {
		return x.CpuLimitCores
	}
	return 0
}

func (x *ProcessStatus) GetMemoryRssBytes() int64 {
	if x != nil {
		return x.MemoryRssBytes
	}
	return 0
}

func (x *ProcessStatus) GetMemoryLimitBytes() int64 {
	if x != nil {
		return x.MemoryLimitBytes
	}
	return 0
}

func (x *ProcessStatus) GetGoHeapBytes() int64 {
	if x != nil {
		return x.GoHeapBytes
	}
	return 0
}

func (x *ProcessStatus) GetGoroutines() int32 {
	if x != nil {
		return x.Goroutines
	}
	return 0
}

func (x *ProcessStatus) GetGcCount() uint32 {
	if x != nil {
		return x.GcCount
	}
	return 0
}

func (x *ProcessStatus) GetDiskPath() string {
	if x != nil {
		return x.DiskPath
	}
	return ""
}

func (x *ProcessStatus) GetDiskUsedBytes() int64 {
	if x != nil {
		return x.DiskUsedBytes
	}
	return 0
}

func (x *ProcessStatus) GetDiskTotalBytes() int64 {
	if x != nil {
		return x.DiskTotalBytes
	}
	return 0
}

func (x *ProcessStatus) GetNetRxBytesPerSec() float64 {
	if x != nil {
		return x.NetRxBytesPerSec
	}
	return 0
}

func (x *ProcessStatus) GetNetTxBytesPerSec() float64 {
	if x != nil {
		return x.NetTxBytesPerSec
	}
	return 0
}

func (x *ProcessStatus) GetLimitsFromCgroup() bool {
	if x != nil {
		return x.LimitsFromCgroup
	}
	return false
}

func (x *ProcessStatus) GetSampledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SampledAt
	}
	return nil
}

func (x *ProcessStatus) GetUptime() *durationpb.Duration {
	if x != nil {
		return x.Uptime
	}
	return nil
}

func (x *ProcessStatus) GetDegraded() []string {
	if x != nil {
		return x.Degraded
	}
	return nil
}

type DependencyStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // postgres / redis
	Healthy       bool                   `protobuf:"varint,2,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Detail        string                 `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"` // 不健康时的原因;健康时为空
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DependencyStatus) Reset() {
	*x = DependencyStatus{}
	mi := &file_api_system_v1_system_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DependencyStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DependencyStatus) ProtoMessage() {}

func (x *DependencyStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_system_v1_system_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DependencyStatus.ProtoReflect.Descriptor instead.
func (*DependencyStatus) Descriptor() ([]byte, []int) {
	return file_api_system_v1_system_proto_rawDescGZIP(), []int{3}
}

func (x *DependencyStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DependencyStatus) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *DependencyStatus) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type BuildInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Environment   string                 `protobuf:"bytes,3,opt,name=environment,proto3" json:"environment,omitempty"`
	GoVersion     string                 `protobuf:"bytes,4,opt,name=go_version,json=goVersion,proto3" json:"go_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildInfo) Reset() {
	*x = BuildInfo{}
	mi := &file_api_system_v1_system_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildInfo) ProtoMessage() {}

func (x *BuildInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_system_v1_system_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildInfo.ProtoReflect.Descriptor instead.
func (*BuildInfo) Descriptor() ([]byte, []int) {
	return file_api_system_v1_system_proto_rawDescGZIP(), []int{4}
}

func (x *BuildInfo) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *BuildInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *BuildInfo) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *BuildInfo) GetGoVersion() string {
	if x != nil {
		return x.GoVersion
	}
	return ""
}

type QueryMetricsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 要哪几组曲线。上限 8 组是因为每组会展开成 1~N 条 PromQL,
	// 一次请求打出去的查询数要有个头。
	Series []MetricSeries `protobuf:"varint,1,rep,packed,name=series,proto3,enum=system.v1.MetricSeries" json:"series,omitempty"`
	// 往前看多久。上限 24h:再长就该去 Grafana,那里有下采样和更合适的交互。
	Window *durationpb.Duration `protobuf:"bytes,2,opt,name=window,proto3" json:"window,omitempty"`
	// 采样步长。下限 10s 与 collector 的采集周期一致 —— 比它更细只会得到
	// 一堆插值出来的假点。
	StepSeconds   int32 `protobuf:"varint,3,opt,name=step_seconds,json=stepSeconds,proto3" json:"step_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryMetricsRequest) Reset() {
	*x = QueryMetricsRequest{}
	mi := &file_api_system_v1_system_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryMetricsRequest) ProtoMessage() {}

func (x *QueryMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_system_v1_system_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryMetricsRequest.ProtoReflect.Descriptor instead.
func (*QueryMetricsRequest) Descriptor() ([]byte, []int) {
	return file_api_system_v1_system_proto_rawDescGZIP(), []int{5}
}

func (x *QueryMetricsRequest) GetSeries() []MetricSeries {
	if x != nil {
		return x.Series
	}
	return nil
}

func (x *QueryMetricsRequest) GetWindow() *durationpb.Duration {
	if x != nil {
		return x.Window
	}
	return nil
}

func (x *QueryMetricsRequest) GetStepSeconds() int32 {
	if x != nil {
		return x.StepSeconds
	}
	return 0
}

type MetricPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TsMs          int64                  `protobuf:"varint,1,opt,name=ts_ms,json=tsMs,proto3" json:"ts_ms,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricPoint) Reset() {
	*x = MetricPoint{}
	mi := &file_api_system_v1_system_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricPoint) ProtoMessage() {}

func (x *MetricPoint) ProtoReflect() protoreflect.Message {
	mi := &file_api_system_v1_system_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricPoint.ProtoReflect.Descriptor instead.
func (*MetricPoint) Descriptor() ([]byte, []int) {
	return file_api_system_v1_system_proto_rawDescGZIP(), []int{6}
}

func (x *MetricPoint) GetTsMs() int64 {
	if x != nil {
		return x.TsMs
	}
	return 0
}

func (x *MetricPoint) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type MetricLine struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 图例名。P95 / node2 / GetKey 这类,由服务端从查询结果的标签里取,
	// 前端直接展示,不做二次解释。
	Label         string         `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Unit          MetricUnit     `protobuf:"varint,2,opt,name=unit,proto3,enum=system.v1.MetricUnit" json:"unit,omitempty"`
	Points        []*MetricPoint `protobuf:"bytes,3,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricLine) Reset() {
	*x = MetricLine{}
	mi := &file_api_system_v1_system_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricLine) ProtoMessage() {}

func (x *MetricLine) ProtoReflect() protoreflect.Message {
	mi := &file_api_system_v1_system_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricLine.ProtoReflect.Descriptor instead.
func (*MetricLine) Descriptor() ([]byte, []int) {
	return file_api_system_v1_system_proto_rawDescGZIP(), []int{7}
}

func (x *MetricLine) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *MetricLine) GetUnit() MetricUnit {
	if x != nil {
		return x.Unit
	}
	return MetricUnit_METRIC_UNIT_UNSPECIFIED
}

func (x *MetricLine) GetPoints() []*MetricPoint {
	if x != nil {
		return x.Points
	}
	return nil
}

type SeriesResult struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Series MetricSeries           `protobuf:"varint,1,opt,name=series,proto3,enum=system.v1.MetricSeries" json:"series,omitempty"`
	Lines  []*MetricLine          `protobuf:"bytes,2,rep,name=lines,proto3" json:"lines,omitempty"`
	// 该组查询失败的原因。单组失败不影响其他组返回 —— 一个指标暂时没数据
	// 不该让整页空白。
	Error         string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeriesResult) Reset() {
	*x = SeriesResult{}
	mi := &file_api_system_v1_system_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeriesResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeriesResult) ProtoMessage() {}

func (x *SeriesResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_system_v1_system_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeriesResult.ProtoReflect.Descriptor instead.
func (*SeriesResult) Descriptor() ([]byte, []int) {
	return file_api_system_v1_system_proto_rawDescGZIP(), []int{8}
}

func (x *SeriesResult) GetSeries() MetricSeries {
	if x != nil {
		return x.Series
	}
	return MetricSeries_METRIC_SERIES_UNSPECIFIED
}

func (x *SeriesResult) GetLines() []*MetricLine {
	if x != nil {
		return x.Lines
	}
	return nil
}

func (x *SeriesResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type QueryMetricsResponse struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Results                 []*SeriesResult        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	MetricsBackendAvailable bool                   `protobuf:"varint,2,opt,name=metrics_backend_available,json=metricsBackendAvailable,proto3" json:"metrics_backend_available,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *QueryMetricsResponse) Reset() {
	*x = QueryMetricsResponse{}
	mi := &file_api_system_v1_system_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryMetricsResponse) ProtoMessage() {}

func (x *QueryMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_system_v1_system_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryMetricsResponse.ProtoReflect.Descriptor instead.
func (*QueryMetricsResponse) Descriptor() ([]byte, []int) {
	return file_api_system_v1_system_proto_rawDescGZIP(), []int{9}
}

func (x *QueryMetricsResponse) GetResults() []*SeriesResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *QueryMetricsResponse) GetMetricsBackendAvailable() bool {
	if x != nil {
		return x.MetricsBackendAvailable
	}
	return false
}

var File_api_system_v1_system_proto protoreflect.FileDescriptor

const file_api_system_v1_system_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/system/v1/system.proto\x12\tsystem.v1\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a#third_party/validate/validate.proto\"\x18\n" +
	"\x16GetSystemStatusRequest\"\xf6\x01\n" +
	"\x17GetSystemStatusResponse\x122\n" +
	"\aprocess\x18\x01 \x01(\v2\x18.system.v1.ProcessStatusR\aprocess\x12?\n" +
	"\fdependencies\x18\x02 \x03(\v2\x1b.system.v1.DependencyStatusR\fdependencies\x12*\n" +
	"\x05build\x18\x03 \x01(\v2\x14.system.v1.BuildInfoR\x05build\x12:\n" +
	"\x19metrics_backend_available\x18\x04 \x01(\bR\x17metricsBackendAvailable\"\x96\x05\n" +
	"\rProcessStatus\x12\x1f\n" +
	"\vcpu_percent\x18\x01 \x01(\x01R\n" +
	"cpuPercent\x12&\n" +
	"\x0fcpu_limit_cores\x18\x02 \x01(\x01R\rcpuLimitCores\x12(\n" +
	"\x10memory_rss_bytes\x18\x03 \x01(\x03R\x0ememoryRssBytes\x12,\n" +
	"\x12memory_limit_bytes\x18\x04 \x01(\x03R\x10memoryLimitBytes\x12\"\n" +
	"\rgo_heap_bytes\x18\x05 \x01(\x03R\vgoHeapBytes\x12\x1e\n" +
	"\n" +
	"goroutines\x18\x06 \x01(\x05R\n" +
	"goroutines\x12\x19\n" +
	"\bgc_count\x18\a \x01(\rR\agcCount\x12\x1b\n" +
	"\tdisk_path\x18\b \x01(\tR\bdiskPath\x12&\n" +
	"\x0fdisk_used_bytes\x18\t \x01(\x03R\rdiskUsedBytes\x12(\n" +
	"\x10disk_total_bytes\x18\n" +
	" \x01(\x03R\x0ediskTotalBytes\x12.\n" +
	"\x14net_rx_bytes_per_sec\x18\v \x01(\x01R\x10netRxBytesPerSec\x12.\n" +
	"\x14net_tx_bytes_per_sec\x18\f \x01(\x01R\x10netTxBytesPerSec\x12,\n" +
	"\x12limits_from_cgroup\x18\r \x01(\bR\x10limitsFromCgroup\x129\n" +
	"\n" +
	"sampled_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tsampledAt\x121\n" +
	"\x06uptime\x18\x0f \x01(\v2\x19.google.protobuf.DurationR\x06uptime\x12\x1a\n" +
	"\bdegraded\x18\x10 \x03(\tR\bdegraded\"X\n" +
	"\x10DependencyStatus\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\ahealthy\x18\x02 \x01(\bR\ahealthy\x12\x16\n" +
	"\x06detail\x18\x03 \x01(\tR\x06detail\"\x89\x01\n" +
	"\tBuildInfo\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12 \n" +
	"\venvironment\x18\x03 \x01(\tR\venvironment\x12\x1d\n" +
	"\n" +
	"go_version\x18\x04 \x01(\tR\tgoVersion\"\xd5\x01\n" +
	"\x13QueryMetricsRequest\x12F\n" +
	"\x06series\x18\x01 \x03(\x0e2\x17.system.v1.MetricSeriesB\x15\xbaH\x12\x92\x01\x0f\b\x01\x10\b\x18\x01\"\a\x82\x01\x04\x10\x01 \x00R\x06series\x12G\n" +
	"\x06window\x18\x02 \x01(\v2\x19.google.protobuf.DurationB\x14\xbaH\x11\xc8\x01\x01\xaa\x01\v\"\x04\b\x80\xa3\x052\x03\b\xac\x02R\x06window\x12-\n" +
	"\fstep_seconds\x18\x03 \x01(\x05B\n" +
	"\xbaH\a\x1a\x05\x18\x90\x1c(\n" +
	"R\vstepSeconds\"8\n" +
	"\vMetricPoint\x12\x13\n" +
	"\x05ts_ms\x18\x01 \x01(\x03R\x04tsMs\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\"}\n" +
	"\n" +
	"MetricLine\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12)\n" +
	"\x04unit\x18\x02 \x01(\x0e2\x15.system.v1.MetricUnitR\x04unit\x12.\n" +
	"\x06points\x18\x03 \x03(\v2\x16.system.v1.MetricPointR\x06points\"\x82\x01\n" +
	"\fSeriesResult\x12/\n" +
	"\x06series\x18\x01 \x01(\x0e2\x17.system.v1.MetricSeriesR\x06series\x12+\n" +
	"\x05lines\x18\x02 \x03(\v2\x15.system.v1.MetricLineR\x05lines\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\x85\x01\n" +
	"\x14QueryMetricsResponse\x121\n" +
	"\aresults\x18\x01 \x03(\v2\x17.system.v1.SeriesResultR\aresults\x12:\n" +
	"\x19metrics_backend_available\x18\x02 \x01(\bR\x17metricsBackendAvailable*\xcb\x03\n" +
	"\fMetricSeries\x12\x1d\n" +
	"\x19METRIC_SERIES_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19METRIC_SERIES_PROCESS_CPU\x10\x01\x12 \n" +
	"\x1cMETRIC_SERIES_PROCESS_MEMORY\x10\x02\x12$\n" +
	" METRIC_SERIES_PROCESS_GOROUTINES\x10\x03\x12!\n" +
	"\x1dMETRIC_SERIES_PROCESS_NETWORK\x10\x04\x12\x1a\n" +
	"\x16METRIC_SERIES_HOST_CPU\x10\n" +
	"\x12\x1d\n" +
	"\x19METRIC_SERIES_HOST_MEMORY\x10\v\x12\x1b\n" +
	"\x17METRIC_SERIES_HOST_DISK\x10\f\x12\x1e\n" +
	"\x1aMETRIC_SERIES_HOST_NETWORK\x10\r\x12\x1d\n" +
	"\x19METRIC_SERIES_API_LATENCY\x10\x14\x12 \n" +
	"\x1cMETRIC_SERIES_API_THROUGHPUT\x10\x15\x12 \n" +
	"\x1cMETRIC_SERIES_API_ERROR_RATE\x10\x16\x12\x1c\n" +
	"\x18METRIC_SERIES_DB_LATENCY\x10\x1e\x12\x19\n" +
	"\x15METRIC_SERIES_DB_POOL\x10\x1f*\xd5\x01\n" +
	"\n" +
	"MetricUnit\x12\x1b\n" +
	"\x17METRIC_UNIT_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13METRIC_UNIT_PERCENT\x10\x01\x12\x15\n" +
	"\x11METRIC_UNIT_BYTES\x10\x02\x12 \n" +
	"\x1cMETRIC_UNIT_BYTES_PER_SECOND\x10\x03\x12\x1c\n" +
	"\x18METRIC_UNIT_MILLISECONDS\x10\x04\x12#\n" +
	"\x1fMETRIC_UNIT_REQUESTS_PER_SECOND\x10\x05\x12\x15\n" +
	"\x11METRIC_UNIT_COUNT\x10\x062\xbe\x01\n" +
	"\rSystemService\x12Z\n" +
	"\x0fGetSystemStatus\x12!.system.v1.GetSystemStatusRequest\x1a\".system.v1.GetSystemStatusResponse\"\x00\x12Q\n" +
	"\fQueryMetrics\x12\x1e.system.v1.QueryMetricsRequest\x1a\x1f.system.v1.QueryMetricsResponse\"\x00B\x9a\x01\n" +
	"\rcom.system.v1B\vSystemProtoP\x01Z7github.com/lens077/control-tower/api/system/v1;systemv1\xa2\x02\x03SXX\xaa\x02\tSystem.V1\xca\x02\tSystem\\V1\xe2\x02\x15System\\V1\\GPBMetadata\xea\x02\n" +
	"System::V1b\x06proto3"

var (
	file_api_system_v1_system_proto_rawDescOnce sync.Once
	file_api_system_v1_system_proto_rawDescData []byte
)

func file_api_system_v1_system_proto_rawDescGZIP() []byte {
	file_api_system_v1_system_proto_rawDescOnce.Do(func() {
		file_api_system_v1_system_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_system_v1_system_proto_rawDesc), len(file_api_system_v1_system_proto_rawDesc)))
	})
	return file_api_system_v1_system_proto_rawDescData
}

var file_api_system_v1_system_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_system_v1_system_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_system_v1_system_proto_goTypes = []any{
	(MetricSeries)(0),               // 0: system.v1.MetricSeries
	(MetricUnit)(0),                 // 1: system.v1.MetricUnit
	(*GetSystemStatusRequest)(nil),  // 2: system.v1.GetSystemStatusRequest
	(*GetSystemStatusResponse)(nil), // 3: system.v1.GetSystemStatusResponse
	(*ProcessStatus)(nil),           // 4: system.v1.ProcessStatus
	(*DependencyStatus)(nil),        // 5: system.v1.DependencyStatus
	(*BuildInfo)(nil),               // 6: system.v1.BuildInfo
	(*QueryMetricsRequest)(nil),     // 7: system.v1.QueryMetricsRequest
	(*MetricPoint)(nil),             // 8: system.v1.MetricPoint
	(*MetricLine)(nil),              // 9: system.v1.MetricLine
	(*SeriesResult)(nil),            // 10: system.v1.SeriesResult
	(*QueryMetricsResponse)(nil),    // 11: system.v1.QueryMetricsResponse
	(*timestamppb.Timestamp)(nil),   // 12: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),     // 13: google.protobuf.Duration
}
var file_api_system_v1_system_proto_depIdxs = []int32{
	4,  // 0: system.v1.GetSystemStatusResponse.process:type_name -> system.v1.ProcessStatus
	5,  // 1: system.v1.GetSystemStatusResponse.dependencies:type_name -> system.v1.DependencyStatus
	6,  // 2: system.v1.GetSystemStatusResponse.build:type_name -> system.v1.BuildInfo
	12, // 3: system.v1.ProcessStatus.sampled_at:type_name -> google.protobuf.Timestamp
	13, // 4: system.v1.ProcessStatus.uptime:type_name -> google.protobuf.Duration
	0,  // 5: system.v1.QueryMetricsRequest.series:type_name -> system.v1.MetricSeries
	13, // 6: system.v1.QueryMetricsRequest.window:type_name -> google.protobuf.Duration
	1,  // 7: system.v1.MetricLine.unit:type_name -> system.v1.MetricUnit
	8,  // 8: system.v1.MetricLine.points:type_name -> system.v1.MetricPoint
	0,  // 9: system.v1.SeriesResult.series:type_name -> system.v1.MetricSeries
	9,  // 10: system.v1.SeriesResult.lines:type_name -> system.v1.MetricLine
	10, // 11: system.v1.QueryMetricsResponse.results:type_name -> system.v1.SeriesResult
	2,  // 12: system.v1.SystemService.GetSystemStatus:input_type -> system.v1.GetSystemStatusRequest
	7,  // 13: system.v1.SystemService.QueryMetrics:input_type -> system.v1.QueryMetricsRequest
	3,  // 14: system.v1.SystemService.GetSystemStatus:output_type -> system.v1.GetSystemStatusResponse
	11, // 15: system.v1.SystemService.QueryMetrics:output_type -> system.v1.QueryMetricsResponse
	14, // [14:16] is the sub-list for method output_type
	12, // [12:14] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_api_system_v1_system_proto_init() }
func file_api_system_v1_system_proto_init() {
	if File_api_system_v1_system_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_system_v1_system_proto_rawDesc), len(file_api_system_v1_system_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_system_v1_system_proto_goTypes,
		DependencyIndexes: file_api_system_v1_system_proto_depIdxs,
		EnumInfos:         file_api_system_v1_system_proto_enumTypes,
		MessageInfos:      file_api_system_v1_system_proto_msgTypes,
	}.Build()
	File_api_system_v1_system_proto = out.File
	file_api_system_v1_system_proto_goTypes = nil
	file_api_system_v1_system_proto_depIdxs = nil
}
