// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: services/gateway/internal/conf/v1/route.proto

// 网关动态路由配置（RouteConfig）。
// 载体：Config Center 键 gateway/<env>/routes.yaml（YAML → JSON → protojson 解码后经 protovalidate 校验）。
// 可审查模板：仓库根 routes/{dev,pre}.yaml。设计依据：docs/design/architecture.md「配置与自举」。
// 本文件是网关私有契约（非 api/ 公共面），不受 wire 冻结约束；字段校验规则遵循
// ecommerce context/team/proto-design.md：字符串必有上限、repeated 必有 max_items、时长约束范围。

package confv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RouteConfig 是 routes.yaml 的整体形状。热更新按整份原子替换（last-known-good 语义）。
type RouteConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 配置格式版本，当前固定 v2（v1 是旧 kratos 网关的 config.yaml，两者不共键）。
	Version string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	// 路由表：一级 proto 包名 → 后端目标。至少一条；上限防手滑粘贴整站配置。
	Routes []*Route `protobuf:"bytes,2,rep,name=routes,proto3" json:"routes,omitempty"`
	// 匿名清单：authn 跳过 + authz 跳过共用的单一真相源。
	// 条目是完整 Connect procedure 路径，如 /user.v1.UserService/SignIn。
	Anonymous []string `protobuf:"bytes,3,rep,name=anonymous,proto3" json:"anonymous,omitempty"`
	Auth      *Auth    `protobuf:"bytes,4,opt,name=auth,proto3" json:"auth,omitempty"`
	// CORS 必填：网关是浏览器流量入口，漏配 CORS 等于对前端不可用。
	Cors          *Cors `protobuf:"bytes,5,opt,name=cors,proto3" json:"cors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteConfig) Reset() {
	*x = RouteConfig{}
	mi := &file_services_gateway_internal_conf_v1_route_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteConfig) ProtoMessage() {}

func (x *RouteConfig) ProtoReflect() protoreflect.Message {
	mi := &file_services_gateway_internal_conf_v1_route_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteConfig.ProtoReflect.Descriptor instead.
func (*RouteConfig) Descriptor() ([]byte, []int) {
	return file_services_gateway_internal_conf_v1_route_proto_rawDescGZIP(), []int{0}
}

func (x *RouteConfig) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RouteConfig) GetRoutes() []*Route {
	if x != nil {
		return x.Routes
	}
	return nil
}

func (x *RouteConfig) GetAnonymous() []string {
	if x != nil {
		return x.Anonymous
	}
	return nil
}

func (x *RouteConfig) GetAuth() *Auth {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *RouteConfig) GetCors() *Cors {
	if x != nil {
		return x.Cors
	}
	return nil
}

// Route 把一个一级 proto 包名映射到一个后端目标。
type Route struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 一级 proto 包名（/user.v1.UserService/Method 的 user 段）。
	// 匹配语义：路径首段取第一个「.」之前的子串精确比对，大小写敏感。
	Package string `protobuf:"bytes,1,opt,name=package,proto3" json:"package,omitempty"`
	// 后端目标：discovery:///<consul 注册名> 或 direct://<host:port>（本地调试）。
	Target string `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	// 路由级总超时（含选点与转发全程）。上限防误配成「永不超时」。
	Timeout       *durationpb.Duration `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Route) Reset() {
	*x = Route{}
	mi := &file_services_gateway_internal_conf_v1_route_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Route) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Route) ProtoMessage() {}

func (x *Route) ProtoReflect() protoreflect.Message {
	mi := &file_services_gateway_internal_conf_v1_route_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Route.ProtoReflect.Descriptor instead.
func (*Route) Descriptor() ([]byte, []int) {
	return file_services_gateway_internal_conf_v1_route_proto_rawDescGZIP(), []int{1}
}

func (x *Route) GetPackage() string {
	if x != nil {
		return x.Package
	}
	return ""
}

func (x *Route) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *Route) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

// Auth 承载鉴权面的路由级开关。
type Auth struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 高危路由：本地校验通过后仍实时调 Casdoor 在线校验（fail-close）。
	// 条目是完整 Connect procedure 路径。
	OnlineCheckProcedures []string `protobuf:"bytes,1,rep,name=online_check_procedures,json=onlineCheckProcedures,proto3" json:"online_check_procedures,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Auth) Reset() {
	*x = Auth{}
	mi := &file_services_gateway_internal_conf_v1_route_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Auth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Auth) ProtoMessage() {}

func (x *Auth) ProtoReflect() protoreflect.Message {
	mi := &file_services_gateway_internal_conf_v1_route_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Auth.ProtoReflect.Descriptor instead.
func (*Auth) Descriptor() ([]byte, []int) {
	return file_services_gateway_internal_conf_v1_route_proto_rawDescGZIP(), []int{2}
}

func (x *Auth) GetOnlineCheckProcedures() []string {
	if x != nil {
		return x.OnlineCheckProcedures
	}
	return nil
}

// Cors 逐字承载旧网关的跨域策略。
type Cors struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// allow_credentials=true 时 allow_origins 禁止通配符（校验在加载器里做，CEL 不易表达跨字段含通配语义）。
	AllowCredentials bool     `protobuf:"varint,1,opt,name=allow_credentials,json=allowCredentials,proto3" json:"allow_credentials,omitempty"`
	AllowOrigins     []string `protobuf:"bytes,2,rep,name=allow_origins,json=allowOrigins,proto3" json:"allow_origins,omitempty"`
	AllowHeaders     []string `protobuf:"bytes,3,rep,name=allow_headers,json=allowHeaders,proto3" json:"allow_headers,omitempty"`
	AllowMethods     []string `protobuf:"bytes,4,rep,name=allow_methods,json=allowMethods,proto3" json:"allow_methods,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Cors) Reset() {
	*x = Cors{}
	mi := &file_services_gateway_internal_conf_v1_route_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cors) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cors) ProtoMessage() {}

func (x *Cors) ProtoReflect() protoreflect.Message {
	mi := &file_services_gateway_internal_conf_v1_route_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cors.ProtoReflect.Descriptor instead.
func (*Cors) Descriptor() ([]byte, []int) {
	return file_services_gateway_internal_conf_v1_route_proto_rawDescGZIP(), []int{3}
}

func (x *Cors) GetAllowCredentials() bool {
	if x != nil {
		return x.AllowCredentials
	}
	return false
}

func (x *Cors) GetAllowOrigins() []string {
	if x != nil {
		return x.AllowOrigins
	}
	return nil
}

func (x *Cors) GetAllowHeaders() []string {
	if x != nil {
		return x.AllowHeaders
	}
	return nil
}

func (x *Cors) GetAllowMethods() []string {
	if x != nil {
		return x.AllowMethods
	}
	return nil
}

var File_services_gateway_internal_conf_v1_route_proto protoreflect.FileDescriptor

const file_services_gateway_internal_conf_v1_route_proto_rawDesc = "" +
	"\n" +
	"-services/gateway/internal/conf/v1/route.proto\x12\x0fgateway.conf.v1\x1a\x1egoogle/protobuf/duration.proto\x1a#third_party/validate/validate.proto\"\x81\x02\n" +
	"\vRouteConfig\x12#\n" +
	"\aversion\x18\x01 \x01(\tB\t\xbaH\x06r\x04R\x02v2R\aversion\x12:\n" +
	"\x06routes\x18\x02 \x03(\v2\x16.gateway.conf.v1.RouteB\n" +
	"\xbaH\a\x92\x01\x04\b\x01\x10@R\x06routes\x123\n" +
	"\tanonymous\x18\x03 \x03(\tB\x15\xbaH\x12\x92\x01\x0f\x10\x80\x01\"\n" +
	"r\b\x10\x03\x18\x80\x02:\x01/R\tanonymous\x12)\n" +
	"\x04auth\x18\x04 \x01(\v2\x15.gateway.conf.v1.AuthR\x04auth\x121\n" +
	"\x04cors\x18\x05 \x01(\v2\x15.gateway.conf.v1.CorsB\x06\xbaH\x03\xc8\x01\x01R\x04cors\"\xdb\x01\n" +
	"\x05Route\x126\n" +
	"\apackage\x18\x01 \x01(\tB\x1c\xbaH\x19r\x17\x10\x01\x18@2\x11^[a-z][a-z0-9_]*$R\apackage\x12O\n" +
	"\x06target\x18\x02 \x01(\tB7\xbaH4r2\x10\f\x18\x80\x022+^(discovery:///|direct://)[a-zA-Z0-9._:-]+$R\x06target\x12I\n" +
	"\atimeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationB\x14\xbaH\x11\xc8\x01\x01\xaa\x01\v\"\x02\bx2\x05\x10\x80\xc2\xd7/R\atimeout\"T\n" +
	"\x04Auth\x12L\n" +
	"\x17online_check_procedures\x18\x01 \x03(\tB\x14\xbaH\x11\x92\x01\x0e\x10@\"\n" +
	"r\b\x10\x03\x18\x80\x02:\x01/R\x15onlineCheckProcedures\"\xdc\x01\n" +
	"\x04Cors\x12+\n" +
	"\x11allow_credentials\x18\x01 \x01(\bR\x10allowCredentials\x128\n" +
	"\rallow_origins\x18\x02 \x03(\tB\x13\xbaH\x10\x92\x01\r\b\x01\x10 \"\ar\x05\x10\a\x18\x80\x02R\fallowOrigins\x126\n" +
	"\rallow_headers\x18\x03 \x03(\tB\x11\xbaH\x0e\x92\x01\v\x10@\"\ar\x05\x10\x01\x18\x80\x01R\fallowHeaders\x125\n" +
	"\rallow_methods\x18\x04 \x03(\tB\x10\xbaH\r\x92\x01\n" +
	"\x10\x10\"\x06r\x04\x10\x03\x18\x10R\fallowMethodsB\xca\x01\n" +
	"\x13com.gateway.conf.v1B\n" +
	"RouteProtoP\x01ZIgithub.com/lens077/control-tower/services/gateway/internal/conf/v1;confv1\xa2\x02\x03GCX\xaa\x02\x0fGateway.Conf.V1\xca\x02\x0fGateway\\Conf\\V1\xe2\x02\x1bGateway\\Conf\\V1\\GPBMetadata\xea\x02\x11Gateway::Conf::V1b\x06proto3"

var (
	file_services_gateway_internal_conf_v1_route_proto_rawDescOnce sync.Once
	file_services_gateway_internal_conf_v1_route_proto_rawDescData []byte
)

func file_services_gateway_internal_conf_v1_route_proto_rawDescGZIP() []byte {
	file_services_gateway_internal_conf_v1_route_proto_rawDescOnce.Do(func() {
		file_services_gateway_internal_conf_v1_route_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_gateway_internal_conf_v1_route_proto_rawDesc), len(file_services_gateway_internal_conf_v1_route_proto_rawDesc)))
	})
	return file_services_gateway_internal_conf_v1_route_proto_rawDescData
}

var file_services_gateway_internal_conf_v1_route_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_services_gateway_internal_conf_v1_route_proto_goTypes = []any{
	(*RouteConfig)(nil),         // 0: gateway.conf.v1.RouteConfig
	(*Route)(nil),               // 1: gateway.conf.v1.Route
	(*Auth)(nil),                // 2: gateway.conf.v1.Auth
	(*Cors)(nil),                // 3: gateway.conf.v1.Cors
	(*durationpb.Duration)(nil), // 4: google.protobuf.Duration
}
var file_services_gateway_internal_conf_v1_route_proto_depIdxs = []int32{
	1, // 0: gateway.conf.v1.RouteConfig.routes:type_name -> gateway.conf.v1.Route
	2, // 1: gateway.conf.v1.RouteConfig.auth:type_name -> gateway.conf.v1.Auth
	3, // 2: gateway.conf.v1.RouteConfig.cors:type_name -> gateway.conf.v1.Cors
	4, // 3: gateway.conf.v1.Route.timeout:type_name -> google.protobuf.Duration
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_services_gateway_internal_conf_v1_route_proto_init() }
func file_services_gateway_internal_conf_v1_route_proto_init() {
	if File_services_gateway_internal_conf_v1_route_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_gateway_internal_conf_v1_route_proto_rawDesc), len(file_services_gateway_internal_conf_v1_route_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_services_gateway_internal_conf_v1_route_proto_goTypes,
		DependencyIndexes: file_services_gateway_internal_conf_v1_route_proto_depIdxs,
		MessageInfos:      file_services_gateway_internal_conf_v1_route_proto_msgTypes,
	}.Build()
	File_services_gateway_internal_conf_v1_route_proto = out.File
	file_services_gateway_internal_conf_v1_route_proto_goTypes = nil
	file_services_gateway_internal_conf_v1_route_proto_depIdxs = nil
}
