// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: machine_tokens.sql

package models

import (
	"context"

	"github.com/google/uuid"
)

const GetActiveMachineTokenByHash = `-- name: GetActiveMachineTokenByHash :one
SELECT id, service_name, environment, token_hash, allowed_namespaces, note, disabled, created_at, revoked_at, last_used_at FROM config.machine_token
WHERE token_hash = $1 AND NOT disabled
`

// GetActiveMachineTokenByHash
//
//	SELECT id, service_name, environment, token_hash, allowed_namespaces, note, disabled, created_at, revoked_at, last_used_at FROM config.machine_token
//	WHERE token_hash = $1 AND NOT disabled
func (q *Queries) GetActiveMachineTokenByHash(ctx context.Context, tokenHash []byte) (ConfigMachineToken, error) {
	row := q.db.QueryRow(ctx, GetActiveMachineTokenByHash, tokenHash)
	var i ConfigMachineToken
	err := row.Scan(
		&i.ID,
		&i.ServiceName,
		&i.Environment,
		&i.TokenHash,
		&i.AllowedNamespaces,
		&i.Note,
		&i.Disabled,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const InsertMachineToken = `-- name: InsertMachineToken :one
INSERT INTO config.machine_token (id, service_name, environment, token_hash, allowed_namespaces, note)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, service_name, environment, token_hash, allowed_namespaces, note, disabled, created_at, revoked_at, last_used_at
`

type InsertMachineTokenParams struct {
	ID                uuid.UUID
	ServiceName       string
	Environment       string
	TokenHash         []byte
	AllowedNamespaces []string
	Note              string
}

// InsertMachineToken
//
//	INSERT INTO config.machine_token (id, service_name, environment, token_hash, allowed_namespaces, note)
//	VALUES ($1, $2, $3, $4, $5, $6)
//	RETURNING id, service_name, environment, token_hash, allowed_namespaces, note, disabled, created_at, revoked_at, last_used_at
func (q *Queries) InsertMachineToken(ctx context.Context, arg InsertMachineTokenParams) (ConfigMachineToken, error) {
	row := q.db.QueryRow(ctx, InsertMachineToken,
		arg.ID,
		arg.ServiceName,
		arg.Environment,
		arg.TokenHash,
		arg.AllowedNamespaces,
		arg.Note,
	)
	var i ConfigMachineToken
	err := row.Scan(
		&i.ID,
		&i.ServiceName,
		&i.Environment,
		&i.TokenHash,
		&i.AllowedNamespaces,
		&i.Note,
		&i.Disabled,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const IsMachineTokenActive = `-- name: IsMachineTokenActive :one
SELECT EXISTS (
  SELECT 1 FROM config.machine_token WHERE id = $1 AND NOT disabled
) AS active
`

// IsMachineTokenActive
//
//	SELECT EXISTS (
//	  SELECT 1 FROM config.machine_token WHERE id = $1 AND NOT disabled
//	) AS active
func (q *Queries) IsMachineTokenActive(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, IsMachineTokenActive, id)
	var active bool
	err := row.Scan(&active)
	return active, err
}

const ListMachineTokens = `-- name: ListMachineTokens :many
SELECT id, service_name, environment, token_hash, allowed_namespaces, note, disabled, created_at, revoked_at, last_used_at FROM config.machine_token
WHERE ($1::text IS NULL OR service_name = $1)
  AND ($2::text IS NULL OR environment = $2)
ORDER BY service_name, environment, created_at
`

type ListMachineTokensParams struct {
	ServiceName *string
	Environment *string
}

// ListMachineTokens
//
//	SELECT id, service_name, environment, token_hash, allowed_namespaces, note, disabled, created_at, revoked_at, last_used_at FROM config.machine_token
//	WHERE ($1::text IS NULL OR service_name = $1)
//	  AND ($2::text IS NULL OR environment = $2)
//	ORDER BY service_name, environment, created_at
func (q *Queries) ListMachineTokens(ctx context.Context, arg ListMachineTokensParams) ([]ConfigMachineToken, error) {
	rows, err := q.db.Query(ctx, ListMachineTokens, arg.ServiceName, arg.Environment)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ConfigMachineToken
	for rows.Next() {
		var i ConfigMachineToken
		if err := rows.Scan(
			&i.ID,
			&i.ServiceName,
			&i.Environment,
			&i.TokenHash,
			&i.AllowedNamespaces,
			&i.Note,
			&i.Disabled,
			&i.CreatedAt,
			&i.RevokedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const RevokeMachineToken = `-- name: RevokeMachineToken :one
UPDATE config.machine_token
SET disabled = TRUE, revoked_at = now()
WHERE id = $1 AND NOT disabled
RETURNING id, service_name, environment, token_hash, allowed_namespaces, note, disabled, created_at, revoked_at, last_used_at
`

// RevokeMachineToken
//
//	UPDATE config.machine_token
//	SET disabled = TRUE, revoked_at = now()
//	WHERE id = $1 AND NOT disabled
//	RETURNING id, service_name, environment, token_hash, allowed_namespaces, note, disabled, created_at, revoked_at, last_used_at
func (q *Queries) RevokeMachineToken(ctx context.Context, id uuid.UUID) (ConfigMachineToken, error) {
	row := q.db.QueryRow(ctx, RevokeMachineToken, id)
	var i ConfigMachineToken
	err := row.Scan(
		&i.ID,
		&i.ServiceName,
		&i.Environment,
		&i.TokenHash,
		&i.AllowedNamespaces,
		&i.Note,
		&i.Disabled,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const TouchMachineTokenLastUsed = `-- name: TouchMachineTokenLastUsed :exec
UPDATE config.machine_token SET last_used_at = now() WHERE id = $1
`

// TouchMachineTokenLastUsed
//
//	UPDATE config.machine_token SET last_used_at = now() WHERE id = $1
func (q *Queries) TouchMachineTokenLastUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, TouchMachineTokenLastUsed, id)
	return err
}
