// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/sdk/v1/source.proto

package sdkv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SourceConfig_Type int32

const (
	SourceConfig_TYPE_UNSPECIFIED   SourceConfig_Type = 0
	SourceConfig_TYPE_FILE          SourceConfig_Type = 1
	SourceConfig_TYPE_CONSUL        SourceConfig_Type = 2
	SourceConfig_TYPE_CONFIG_CENTER SourceConfig_Type = 3
)

// Enum value maps for SourceConfig_Type.
var (
	SourceConfig_Type_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "TYPE_FILE",
		2: "TYPE_CONSUL",
		3: "TYPE_CONFIG_CENTER",
	}
	SourceConfig_Type_value = map[string]int32{
		"TYPE_UNSPECIFIED":   0,
		"TYPE_FILE":          1,
		"TYPE_CONSUL":        2,
		"TYPE_CONFIG_CENTER": 3,
	}
)

func (x SourceConfig_Type) Enum() *SourceConfig_Type {
	p := new(SourceConfig_Type)
	*p = x
	return p
}

func (x SourceConfig_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SourceConfig_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_api_sdk_v1_source_proto_enumTypes[0].Descriptor()
}

func (SourceConfig_Type) Type() protoreflect.EnumType {
	return &file_api_sdk_v1_source_proto_enumTypes[0]
}

func (x SourceConfig_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SourceConfig_Type.Descriptor instead.
func (SourceConfig_Type) EnumDescriptor() ([]byte, []int) {
	return file_api_sdk_v1_source_proto_rawDescGZIP(), []int{0, 0}
}

// SourceConfig is the local bootstrap configuration used before a service can
// load its business Bootstrap. It intentionally lives outside the remote
// configuration document so a source-selection cycle is impossible.
type SourceConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          SourceConfig_Type      `protobuf:"varint,1,opt,name=type,proto3,enum=configcenter.sdk.v1.SourceConfig_Type" json:"type,omitempty"`
	File          *File                  `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty"`
	Consul        *Consul                `protobuf:"bytes,3,opt,name=consul,proto3" json:"consul,omitempty"`
	ConfigCenter  *ConfigCenter          `protobuf:"bytes,4,opt,name=config_center,json=configCenter,proto3" json:"config_center,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourceConfig) Reset() {
	*x = SourceConfig{}
	mi := &file_api_sdk_v1_source_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceConfig) ProtoMessage() {}

func (x *SourceConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_sdk_v1_source_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceConfig.ProtoReflect.Descriptor instead.
func (*SourceConfig) Descriptor() ([]byte, []int) {
	return file_api_sdk_v1_source_proto_rawDescGZIP(), []int{0}
}

func (x *SourceConfig) GetType() SourceConfig_Type {
	if x != nil {
		return x.Type
	}
	return SourceConfig_TYPE_UNSPECIFIED
}

func (x *SourceConfig) GetFile() *File {
	if x != nil {
		return x.File
	}
	return nil
}

func (x *SourceConfig) GetConsul() *Consul {
	if x != nil {
		return x.Consul
	}
	return nil
}

func (x *SourceConfig) GetConfigCenter() *ConfigCenter {
	if x != nil {
		return x.ConfigCenter
	}
	return nil
}

type File struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *File) Reset() {
	*x = File{}
	mi := &file_api_sdk_v1_source_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_api_sdk_v1_source_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_api_sdk_v1_source_proto_rawDescGZIP(), []int{1}
}

func (x *File) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type Consul struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Address            string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Key                string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Scheme             string                 `protobuf:"bytes,3,opt,name=scheme,proto3" json:"scheme,omitempty"`
	Token              string                 `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	InsecureSkipVerify bool                   `protobuf:"varint,5,opt,name=insecure_skip_verify,json=insecureSkipVerify,proto3" json:"insecure_skip_verify,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Consul) Reset() {
	*x = Consul{}
	mi := &file_api_sdk_v1_source_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Consul) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Consul) ProtoMessage() {}

func (x *Consul) ProtoReflect() protoreflect.Message {
	mi := &file_api_sdk_v1_source_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Consul.ProtoReflect.Descriptor instead.
func (*Consul) Descriptor() ([]byte, []int) {
	return file_api_sdk_v1_source_proto_rawDescGZIP(), []int{2}
}

func (x *Consul) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Consul) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Consul) GetScheme() string {
	if x != nil {
		return x.Scheme
	}
	return ""
}

func (x *Consul) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *Consul) GetInsecureSkipVerify() bool {
	if x != nil {
		return x.InsecureSkipVerify
	}
	return false
}

type ConfigCenter struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Address     string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Namespace   string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Environment string                 `protobuf:"bytes,3,opt,name=environment,proto3" json:"environment,omitempty"`
	Key         string                 `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"`
	// Service credentials belong in a local, ignored source file or secret mount.
	ServiceToken string `protobuf:"bytes,5,opt,name=service_token,json=serviceToken,proto3" json:"service_token,omitempty"`
	// Client identity is observability metadata. It is not an authorization credential.
	ClientName     string `protobuf:"bytes,6,opt,name=client_name,json=clientName,proto3" json:"client_name,omitempty"`
	ClientInstance string `protobuf:"bytes,7,opt,name=client_instance,json=clientInstance,proto3" json:"client_instance,omitempty"`
	ClientVersion  string `protobuf:"bytes,8,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConfigCenter) Reset() {
	*x = ConfigCenter{}
	mi := &file_api_sdk_v1_source_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigCenter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigCenter) ProtoMessage() {}

func (x *ConfigCenter) ProtoReflect() protoreflect.Message {
	mi := &file_api_sdk_v1_source_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigCenter.ProtoReflect.Descriptor instead.
func (*ConfigCenter) Descriptor() ([]byte, []int) {
	return file_api_sdk_v1_source_proto_rawDescGZIP(), []int{3}
}

func (x *ConfigCenter) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ConfigCenter) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ConfigCenter) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *ConfigCenter) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ConfigCenter) GetServiceToken() string {
	if x != nil {
		return x.ServiceToken
	}
	return ""
}

func (x *ConfigCenter) GetClientName() string {
	if x != nil {
		return x.ClientName
	}
	return ""
}

func (x *ConfigCenter) GetClientInstance() string {
	if x != nil {
		return x.ClientInstance
	}
	return ""
}

func (x *ConfigCenter) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

var File_api_sdk_v1_source_proto protoreflect.FileDescriptor

const file_api_sdk_v1_source_proto_rawDesc = "" +
	"\n" +
	"\x17api/sdk/v1/source.proto\x12\x13configcenter.sdk.v1\x1a#third_party/validate/validate.proto\"\xd8\x02\n" +
	"\fSourceConfig\x12F\n" +
	"\x04type\x18\x01 \x01(\x0e2&.configcenter.sdk.v1.SourceConfig.TypeB\n" +
	"\xbaH\a\x82\x01\x04\x10\x01 \x00R\x04type\x12-\n" +
	"\x04file\x18\x02 \x01(\v2\x19.configcenter.sdk.v1.FileR\x04file\x123\n" +
	"\x06consul\x18\x03 \x01(\v2\x1b.configcenter.sdk.v1.ConsulR\x06consul\x12F\n" +
	"\rconfig_center\x18\x04 \x01(\v2!.configcenter.sdk.v1.ConfigCenterR\fconfigCenter\"T\n" +
	"\x04Type\x12\x14\n" +
	"\x10TYPE_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tTYPE_FILE\x10\x01\x12\x0f\n" +
	"\vTYPE_CONSUL\x10\x02\x12\x16\n" +
	"\x12TYPE_CONFIG_CENTER\x10\x03\"#\n" +
	"\x04File\x12\x1b\n" +
	"\x04path\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x04path\"\xba\x01\n" +
	"\x06Consul\x12!\n" +
	"\aaddress\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\aaddress\x12\x19\n" +
	"\x03key\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x03key\x12*\n" +
	"\x06scheme\x18\x03 \x01(\tB\x12\xbaH\x0fr\rR\x04httpR\x05httpsR\x06scheme\x12\x14\n" +
	"\x05token\x18\x04 \x01(\tR\x05token\x120\n" +
	"\x14insecure_skip_verify\x18\x05 \x01(\bR\x12insecureSkipVerify\"\xb4\x02\n" +
	"\fConfigCenter\x12!\n" +
	"\aaddress\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\aaddress\x12%\n" +
	"\tnamespace\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\tnamespace\x12)\n" +
	"\venvironment\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\venvironment\x12\x19\n" +
	"\x03key\x18\x04 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x03key\x12#\n" +
	"\rservice_token\x18\x05 \x01(\tR\fserviceToken\x12\x1f\n" +
	"\vclient_name\x18\x06 \x01(\tR\n" +
	"clientName\x12'\n" +
	"\x0fclient_instance\x18\a \x01(\tR\x0eclientInstance\x12%\n" +
	"\x0eclient_version\x18\b \x01(\tR\rclientVersionB\xc7\x01\n" +
	"\x17com.configcenter.sdk.v1B\vSourceProtoP\x01Z1github.com/lens077/control-tower/api/sdk/v1;sdkv1\xa2\x02\x03CSX\xaa\x02\x13Configcenter.Sdk.V1\xca\x02\x13Configcenter\\Sdk\\V1\xe2\x02\x1fConfigcenter\\Sdk\\V1\\GPBMetadata\xea\x02\x15Configcenter::Sdk::V1b\x06proto3"

var (
	file_api_sdk_v1_source_proto_rawDescOnce sync.Once
	file_api_sdk_v1_source_proto_rawDescData []byte
)

func file_api_sdk_v1_source_proto_rawDescGZIP() []byte {
	file_api_sdk_v1_source_proto_rawDescOnce.Do(func() {
		file_api_sdk_v1_source_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_sdk_v1_source_proto_rawDesc), len(file_api_sdk_v1_source_proto_rawDesc)))
	})
	return file_api_sdk_v1_source_proto_rawDescData
}

var file_api_sdk_v1_source_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_sdk_v1_source_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_sdk_v1_source_proto_goTypes = []any{
	(SourceConfig_Type)(0), // 0: configcenter.sdk.v1.SourceConfig.Type
	(*SourceConfig)(nil),   // 1: configcenter.sdk.v1.SourceConfig
	(*File)(nil),           // 2: configcenter.sdk.v1.File
	(*Consul)(nil),         // 3: configcenter.sdk.v1.Consul
	(*ConfigCenter)(nil),   // 4: configcenter.sdk.v1.ConfigCenter
}
var file_api_sdk_v1_source_proto_depIdxs = []int32{
	0, // 0: configcenter.sdk.v1.SourceConfig.type:type_name -> configcenter.sdk.v1.SourceConfig.Type
	2, // 1: configcenter.sdk.v1.SourceConfig.file:type_name -> configcenter.sdk.v1.File
	3, // 2: configcenter.sdk.v1.SourceConfig.consul:type_name -> configcenter.sdk.v1.Consul
	4, // 3: configcenter.sdk.v1.SourceConfig.config_center:type_name -> configcenter.sdk.v1.ConfigCenter
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_sdk_v1_source_proto_init() }
func file_api_sdk_v1_source_proto_init() {
	if File_api_sdk_v1_source_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_sdk_v1_source_proto_rawDesc), len(file_api_sdk_v1_source_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_sdk_v1_source_proto_goTypes,
		DependencyIndexes: file_api_sdk_v1_source_proto_depIdxs,
		EnumInfos:         file_api_sdk_v1_source_proto_enumTypes,
		MessageInfos:      file_api_sdk_v1_source_proto_msgTypes,
	}.Build()
	File_api_sdk_v1_source_proto = out.File
	file_api_sdk_v1_source_proto_goTypes = nil
	file_api_sdk_v1_source_proto_depIdxs = nil
}
