{{- if .Values.gateway.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: control-tower-gateway
  namespace: {{ .Values.gateway.namespace }}
automountServiceAccountToken: false
{{- end }}
