/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceRouteImport } from './routes/_workspace'
import { Route as ConnectionsRouteImport } from './routes/connections'
import { Route as SystemRouteImport } from './routes/system'
import { Route as TokensRouteImport } from './routes/tokens'
import { Route as WorkspaceIndexRouteImport } from './routes/_workspace/index'
import { Route as WorkspaceEditRouteImport } from './routes/_workspace/edit'
import { Route as WorkspaceHistoryRouteImport } from './routes/_workspace/history'
import { Route as CallbackIndexRouteImport } from './routes/callback/index'

const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/_workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionsRoute = ConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemRoute = SystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => rootRouteImport,
} as any)
const TokensRoute = TokensRouteImport.update({
  id: '/tokens',
  path: '/tokens',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceIndexRoute = WorkspaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceEditRoute = WorkspaceEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceHistoryRoute = WorkspaceHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => WorkspaceRoute,
} as any)
const CallbackIndexRoute = CallbackIndexRouteImport.update({
  id: '/callback/',
  path: '/callback/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof WorkspaceIndexRoute
  '/connections': typeof ConnectionsRoute
  '/system': typeof SystemRoute
  '/tokens': typeof TokensRoute
  '/edit': typeof WorkspaceEditRoute
  '/history': typeof WorkspaceHistoryRoute
  '/callback/': typeof CallbackIndexRoute
}
export interface FileRoutesByTo {
  '/connections': typeof ConnectionsRoute
  '/system': typeof SystemRoute
  '/tokens': typeof TokensRoute
  '/edit': typeof WorkspaceEditRoute
  '/history': typeof WorkspaceHistoryRoute
  '/': typeof WorkspaceIndexRoute
  '/callback': typeof CallbackIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_workspace': typeof WorkspaceRouteWithChildren
  '/connections': typeof ConnectionsRoute
  '/system': typeof SystemRoute
  '/tokens': typeof TokensRoute
  '/_workspace/edit': typeof WorkspaceEditRoute
  '/_workspace/history': typeof WorkspaceHistoryRoute
  '/_workspace/': typeof WorkspaceIndexRoute
  '/callback/': typeof CallbackIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connections'
    | '/system'
    | '/tokens'
    | '/edit'
    | '/history'
    | '/callback/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/connections'
    | '/system'
    | '/tokens'
    | '/edit'
    | '/history'
    | '/'
    | '/callback'
  id:
    | '__root__'
    | '/_workspace'
    | '/connections'
    | '/system'
    | '/tokens'
    | '/_workspace/edit'
    | '/_workspace/history'
    | '/_workspace/'
    | '/callback/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  WorkspaceRoute: typeof WorkspaceRouteWithChildren
  ConnectionsRoute: typeof ConnectionsRoute
  SystemRoute: typeof SystemRoute
  TokensRoute: typeof TokensRoute
  CallbackIndexRoute: typeof CallbackIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_workspace': {
      id: '/_workspace'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connections': {
      id: '/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof ConnectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system': {
      id: '/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof SystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tokens': {
      id: '/tokens'
      path: '/tokens'
      fullPath: '/tokens'
      preLoaderRoute: typeof TokensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace/': {
      id: '/_workspace/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof WorkspaceIndexRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/edit': {
      id: '/_workspace/edit'
      path: '/edit'
      fullPath: '/edit'
      preLoaderRoute: typeof WorkspaceEditRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/history': {
      id: '/_workspace/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof WorkspaceHistoryRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/callback/': {
      id: '/callback/'
      path: '/callback'
      fullPath: '/callback/'
      preLoaderRoute: typeof CallbackIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface WorkspaceRouteChildren {
  WorkspaceEditRoute: typeof WorkspaceEditRoute
  WorkspaceHistoryRoute: typeof WorkspaceHistoryRoute
  WorkspaceIndexRoute: typeof WorkspaceIndexRoute
}

const WorkspaceRouteChildren: WorkspaceRouteChildren = {
  WorkspaceEditRoute: WorkspaceEditRoute,
  WorkspaceHistoryRoute: WorkspaceHistoryRoute,
  WorkspaceIndexRoute: WorkspaceIndexRoute,
}

const WorkspaceRouteWithChildren = WorkspaceRoute._addFileChildren(
  WorkspaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  WorkspaceRoute: WorkspaceRouteWithChildren,
  ConnectionsRoute: ConnectionsRoute,
  SystemRoute: SystemRoute,
  TokensRoute: TokensRoute,
  CallbackIndexRoute: CallbackIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
